---
- hosts: all
  become: yes

  vars_files:
    - vars/defaults.yml

  roles:
      - geerlingguy.postfix


  tasks:
    - name: Install required dependencies
      yum:
        name: cyrus-sasl-plain
        state: latest

    - name: Configure SASL file
      lineinfile:
        create: yes
        path: /etc/postfix/sasl_passwd
        regex: '^{{ relayhost }}'
        line: '{{ relayhost }}:{{ relayport }} {{ relayuser }}:{{ relaypass }}'
      notify: restart postfix
    
    - name: Configure SASL file permissions
      file:
        path: /etc/postfix/sasl_passwd
        owner: root
        group: root
        mode: '0600'


    - name: Configure relayhost 
      lineinfile:
        path: /etc/postfix/main.cf
        regex: "{{ item.regex }}"
        line: "{{ item.line }}"
      with_items:
        - {regex: '^relayhost', line: "relayhost = {{ relayhost }}:{{ relayport }}"}
        - {regex: '^mynetworks', line: "mynetworks = {{ mynetworks }}"}
        - {regex: '^smtp_sasl_password_maps', line: 'smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd'}
        - {regex: '^smtp_sasl_auth_enable', line: 'smtp_sasl_auth_enable = yes'}
        - {regex: '^smtp_sasl_security_options', line: 'smtp_sasl_security_options = noanonymous'}
      notify: restart postfix

    - name: Configure Firewall
      firewalld:
        service: smtp
        permanent: yes
        state: enabled
        immediate: yes
